//#region Why this file
// Two kinds of visitor share `conversations.visitor_id`, and this file is the
// rule that keeps them apart — a cross-package contract because realtime
// enforces it on both session routes and the dashboard reads it to say who a
// conversation was with.
//
//   ANONYMOUS  vis_<32 hex>   minted by POST /v1/widget/session (the browser,
//                             with the publishable key). Generated by the
//                             server; the widget stores it and hands it back
//                             on the next mint so conversations survive a
//                             page reload. Unguessable (128 bits), which is
//                             the whole of its security.
//   IDENTIFIED anything else  minted ONLY by POST /v1/sessions (the customer's
//                             backend, with the SECRET key — trust-model layer
//                             6). The value is the customer's own stable user
//                             identifier: "42", "usr_8f3a…", a UUID.
//
// Why the split has to be a hard rule and not a convention: the browser mint
// accepts a client-supplied visitor id (that is how reloads keep their
// thread), and a customer's user ids are GUESSABLE — sequential integers,
// often. If the browser route took any well-formed id, anyone on an
// allowlisted origin could mint a session as "42" and, to the support agent
// reading the inbox, BE user 42 ("hi, please change my email to…"). That is
// exactly the attack identity verification exists to stop. So the browser
// route accepts only the anonymous shape, the server route refuses it, and a
// visitor id that is not `vis_<hex>` can only have come from the tenant's own
// server — which is what lets the dashboard label it "identified by your
// server" truthfully.
//
// The customer's identifier is stored verbatim rather than prefixed, so the
// dashboard shows the id THEY know. Shape is bounded to what fits an id (no
// spaces, no punctuation beyond _ and -, ≤100 chars — the schema's CHECK on
// visitor_id) and the docs say to send a user id, not an email: nothing here
// should turn our database into a copy of theirs.
//#endregion

//#region Imports
// node:crypto — this file is imported by realtime and by the dashboard, both
// Node. The widget never imports it (it only stores what the server returns).
import { randomBytes } from "node:crypto"
//#endregion

//#region Shapes
/** Every visitor id, anonymous or identified: what a token carries and what
 *  the conversations row stores. */
export const VISITOR_ID_SHAPE = /^[A-Za-z0-9_-]{1,100}$/

/** The anonymous namespace: `vis_` + 16 random bytes as hex. The ONLY shape
 *  the browser mint route issues or accepts. */
export const ANONYMOUS_VISITOR_ID_SHAPE = /^vis_[0-9a-f]{32}$/
//#endregion

//#region Exports
/** A fresh anonymous visitor id — what the browser route mints when the
 *  widget has none stored yet. */
export function newAnonymousVisitorId(): string {
  return `vis_${randomBytes(16).toString("hex")}`
}

export function isAnonymousVisitorId(value: string): boolean {
  return ANONYMOUS_VISITOR_ID_SHAPE.test(value)
}

/** Well-formed AND outside the anonymous namespace: what the secret-key mint
 *  route requires, and what the dashboard may call "identified by your
 *  server" — since nothing else can put such a value in a session token. */
export function isIdentifiedVisitorId(value: string): boolean {
  return VISITOR_ID_SHAPE.test(value) && !ANONYMOUS_VISITOR_ID_SHAPE.test(value)
}
//#endregion
